site_name: Structured Streaming Documentation
theme:
  name: material
  
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
        
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.footer
    - content.tabs.link
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Tour:
    - Welcome: tour/welcome.md
    - Installation: tour/installation.md
    - Quick Example: tour/quick_example.md
    - Overview:
      - Execution Model: tour/overview/execution_model.md
      - Sources and DataFrames: tour/overview/sources.md
      - Spark Operators: tour/overview/spark_operators.md
      - Sinks: tour/overview/sinks.md
    - Stateless Streaming:
      - Selection and Projection: tour/stateless/selection_projection.md
      - Additional Operators: tour/stateless/additional_operators.md
    - Stateful Streaming:
      - Introduction: tour/stateful/introduction.md
      - Concepts:
        - Time Domains: tour/stateful/concepts/time_domains.md
        - Emitting Results: tour/stateful/concepts/emitting_results.md
        - Watermarks: tour/stateful/concepts/watermarks.md
      - Operators:
        - Aggregation: tour/stateful/operators/aggregation.md
        - Deduplication: tour/stateful/operators/deduplication.md
        - Joins: tour/stateful/operators/joins.md
        - (Flat)MapGroupsWithState: tour/stateful/groups_with_state.md
      - Examples: tour/stateful/examples.md
    - Running Streaming Jobs:
      - Triggers and Checkpoints: tour/jobs/triggers_and_checkpoints.md
      - Operational Considerations: tour/jobs/operational_considerations.md
      - Deployment: tour/jobs/deployment.md
  - Guides:
    - Overview: guides/overview.md
    - Reading and Writing Binary Formats:
      - Protobuf: guides/binary_formats/protobuf.md
      - Avro: guides/binary_formats/avro.md
      - Thrift: guides/binary_formats/thrift.md
    - Operations:
      - Monitoring: guides/operations/streaming_query_listeners.md
      - Understanding the SparkUI: guides/operations/spark_ui.md
    - Performance:
      - Optimizations: guides/performance/optimizations.md
      - State Stores: guides/performance/state_stores.md
    - Custom Streaming Logic:
      - (Flat)MapGroupsWithState: guides/custom/groups_with_state.md
      - State Processor: guides/custom/state_processor.md
      - foreach(Batch): guides/custom/foreach_batch.md
  - API Reference:
    - Output Mode: api/output_mode.md